### ISSUE TITLE
SyntaxError: Unexpected token '.' when running esbuild-dev

### ISSUE THREAD

**Issue by franciscohanna92** [gadget-inc/esbuild-dev#36]
Hello! I'm looking for a ts-node-dev replacement and I decided to test this package. 

After installing it, if I try to run our Node + Typescript API with it, I'm getting the following error:
```
yarn run v1.19.0
$ esbuild-dev packages/admin-api/src/server.ts
C:\XXX\XXX\XXX\XXX\node_modules\esbuild-dev\pkg\index.js:91
            project.watcher?.add(filename);
                            ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\XXX\XXX\XXX\XXX\node_modules\esbuild-dev\pkg\esbuild-dev.bin.js:4:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The project is a yarn wokrspaces monorepo and I'm on a Windows 10 machine with Node v.12.22.1

**Comment by airhorns** [comment]
Going to close this with the hope the above config resolved your issue and because we're documenting the config in #38.
